import {
  generateRandomCoordinates,
  generateRandomBoolean,
} from "../js/helpers";

test("Random coordinates generated by generateRandomCoordinates helper always returns coordinates between 0 and 9 inclusive for both elements", () => {
  const coordinates = generateRandomCoordinates();
  expect(coordinates[0]).toBeGreaterThanOrEqual(0);
  expect(coordinates[1]).toBeLessThanOrEqual(9);
});

test("generateRandomBoolean helper always returns either true or false", () => {
  const randomBoolean = generateRandomBoolean();
  expect(typeof randomBoolean).toBe("boolean");
});
